USE [Zoo]
GO

/****** Object:  Table [dbo].[PURCHASE]    Script Date: 3/20/2018 11:28:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PURCHASE](
	[Receipt] [int] NOT NULL,
	[Time] [time](7) NOT NULL,
	[Amount] [money] NOT NULL,
	[Pay_option] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[Store] [int] NOT NULL,
	[Customer] [int] NULL,
 CONSTRAINT [PK__PURCHASE__E66A899447727EAF] PRIMARY KEY CLUSTERED 
(
	[Receipt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PURCHASE]  WITH CHECK ADD  CONSTRAINT [FK_PayOptionType] FOREIGN KEY([Pay_option])
REFERENCES [dbo].[PAY_TYPE] ([ID])
GO

ALTER TABLE [dbo].[PURCHASE] CHECK CONSTRAINT [FK_PayOptionType]
GO

ALTER TABLE [dbo].[PURCHASE]  WITH CHECK ADD  CONSTRAINT [FK_PurchasedByCust] FOREIGN KEY([Customer])
REFERENCES [dbo].[CUSTOMER] ([ID])
GO

ALTER TABLE [dbo].[PURCHASE] CHECK CONSTRAINT [FK_PurchasedByCust]
GO

ALTER TABLE [dbo].[PURCHASE]  WITH CHECK ADD  CONSTRAINT [FK_StoreID] FOREIGN KEY([Store])
REFERENCES [dbo].[STORE] ([ID])
GO

ALTER TABLE [dbo].[PURCHASE] CHECK CONSTRAINT [FK_StoreID]
GO

