USE [Zoo]
GO

/****** Object:  Table [dbo].[PURCHASE_INFO]    Script Date: 3/20/2018 11:28:33 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PURCHASE_INFO](
	[Receipt] [int] NOT NULL,
	[Product] [int] NOT NULL,
	[Price] [decimal](18, 0) NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_PURCHASE_INFO] PRIMARY KEY CLUSTERED 
(
	[Receipt] ASC,
	[Product] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PURCHASE_INFO]  WITH CHECK ADD  CONSTRAINT [FK_ProductBought] FOREIGN KEY([Product])
REFERENCES [dbo].[PRODUCT] ([ID])
GO

ALTER TABLE [dbo].[PURCHASE_INFO] CHECK CONSTRAINT [FK_ProductBought]
GO

ALTER TABLE [dbo].[PURCHASE_INFO]  WITH CHECK ADD  CONSTRAINT [PK_ReceiptNum] FOREIGN KEY([Receipt])
REFERENCES [dbo].[PURCHASE] ([Receipt])
GO

ALTER TABLE [dbo].[PURCHASE_INFO] CHECK CONSTRAINT [PK_ReceiptNum]
GO

