USE [Zoo]
GO

/****** Object:  Table [dbo].[STORE]    Script Date: 3/20/2018 11:28:41 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STORE](
	[ID] [int] NOT NULL,
	[Name] [varchar](25) NOT NULL,
	[Type] [int] NOT NULL,
	[Manager] [int] NOT NULL,
	[Manager_date] [date] NOT NULL,
 CONSTRAINT [PK__STORE__3214EC27B8969E88] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ__STORE__3214EC26B04D776F] UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STORE]  WITH CHECK ADD  CONSTRAINT [FK_ManagerStore] FOREIGN KEY([Manager])
REFERENCES [dbo].[EMPLOYEE] ([ID])
GO

ALTER TABLE [dbo].[STORE] CHECK CONSTRAINT [FK_ManagerStore]
GO

ALTER TABLE [dbo].[STORE]  WITH CHECK ADD  CONSTRAINT [FK_StoreType] FOREIGN KEY([Type])
REFERENCES [dbo].[STORE_TYPE] ([ID])
GO

ALTER TABLE [dbo].[STORE] CHECK CONSTRAINT [FK_StoreType]
GO

